---
- name: Initialize Terraform
  ansible.builtin.command: terraform init -input=false
  args:
    chdir: "{{ terraform_project_dir }}"
  environment:
    TF_VAR_vsphere_server: "{{ vmware_hostname }}"
    TF_VAR_vsphere_user: "{{ vmware_username }}"
    TF_VAR_vsphere_password: "{{ vmware_password }}"
  no_log: true

- name: Create Terraform plan for VMware template
  ansible.builtin.command:
    argv:
      - terraform
      - plan
      - -input=false
      - -out=build_vmware_template.tfplan
      - "-var=template_name={{ template_name }}"
      - "-var=template_ip={{ template_ip }}"
      - "-var=attach_install_iso={{ attach_install_iso | bool | lower }}"
  args:
    chdir: "{{ terraform_project_dir }}"
  environment:
    TF_VAR_vsphere_server: "{{ vmware_hostname }}"
    TF_VAR_vsphere_user: "{{ vmware_username }}"
    TF_VAR_vsphere_password: "{{ vmware_password }}"
  no_log: true
